import { ThemeProvider } from "@/components/theme-provider"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";

import { Toaster } from "@/components/ui/sonner"
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });
import Navbar from '@/components/home/navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          
          <Header/>
          {/* <Navbar/> */}
          <main className="main">
            {children}
          </main>
          <Toaster />
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
